site_name: Ge Wit 't Oit Noit Nie documentatie

nav:
  - Welkom: index.md
  - Over: about.md
  - Jaren:
      - 2025:
          - Over: year/2025/about.md
          - Programma specificaties: year/2025/program_specifications.md
  - Compiler:
      - Algemeen: gpc/index.md
      - Programma specificaties: gpc/program_specifications.md
  - GWTONN Bibliotheek:
      - Algemeen: gwtonn_library/index.md
      - Logger: gwtonn_library/logger.md
      - Programma controller: gwtonn_library/programma_controller.md
  - Hardware: 
      - Busarchitectuur: gwtonn_hardware/bus.md
      - Basismodule Handleiding: gwtonn_hardware/piggyback.md
  - Ontwikkeling:
      - Algemeen: development/index.md
      - Coding conventies: development/coding_conventions.md
      - Git: development/git.md
      - Hardware: development/hardware.md
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      
theme:
  name: material