site_name: Ge Wit 't Oit Noit Nie documentatie

nav:
  - Welkom: index.md
  - Over: about.md
  - Jaren:
      - 2025:
          - Over: year/2025/about.md
          - Programma specificaties: year/2025/program_specifications.md
  - GWTONN Bibliotheek:
      - Algemeen: gwtonn_library/index.md
      - Logger: gwtonn_library/logger.md
      - Programma specificaties: gwtonn_library/programma.md
  - Hardware: 
      - Algemeen: gwtonn_hardware/index.md
      - Busarchitectuur: gwtonn_hardware/bus.md
      - Microcontroller: gwtonn_hardware/uc.md
      - Handleiding: gwtonn_hardware/handleiding.md
  - Ontwikkeling:
      - Algemeen: development/index.md
      - Coding conventies: development/coding_conventions.md
      - Git: development/git.md
      - Hardware: development/hardware.md
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material