site_name: Ge Wit 't Oit Noit Nie documentatie

nav:
  - Welkom: index.md
  - Coding Conventies: coding_conventions.md
  - Over: about.md
  - Jaren:
      - 2025:
          - Over: year/2025/about.md
          - Programma specificaties: year/2025/program_specifications.md
  - GWTONN Bibliotheek:
      - Algemeen: gwtonn_library/index.md
      - Logger: gwtonn_library/logger.md
      - Programma specificaties: gwtonn_library/programma.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material