site_name: Ge Wit 't Oit Noit Nie documentatie

nav:
  - Welkom: index.md
  - Hardware: 
    - Busarchitectuur: gwtonn_hardware/bus.md
    - Basismodule Handleiding: gwtonn_hardware/piggyback.md
  - Software:
    - Index: software/index.md
    - Programma:
        - Algemeen: software/gpc/index.md
        - Programma specificaties: software/gpc/program_specifications.md
    - Firmware:
        - Algemeen: software/firmware/index.md
        - Logger: software/firmware/logger.md
        - Programma controller: software/firmware/programma_controller.md
        - CAN: software/firmware/can.md
  - Guidelines/handleiding:
      - Algemeen: guidelines/index.md
      - Coding conventies: guidelines/coding_conventions.md
      - Git: guidelines/git.md
      - Hardware: guidelines/hardware.md
  - Jaren:
      - 2025:
          - Over: year/2025/about.md
          - Programma specificaties: year/2025/program_specifications.md
  - Site structuur: site_structure.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      
theme:
  name: material