site_name: Ge Wit 't Oit Noit Nie documentatie

nav:
  - Home: index.md
  - Jaren:
      - 2025:
          - Over: year/2025/about.md
          - Programma specificaties: year/2025/program_specifications.md
  - GWTONN Bibliotheek:
      - Programma specificaties: programma.md
      - Coding Conventies: coding_conventions.md
  - Over: about.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - json
    - yaml
    - xml
    - sql
    - dockerfile
    - markdown
    - powershell
    - c