name: Add contributors
on:
  push:
    branches-ignore:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      
    - uses: BobAnkh/add-contributors@master
      name: Add contributors
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/docs/index.md'
        COMMIT_MESSAGE: 'docs(about): update contributors'
        AVATAR_SHAPE: 'round'
        BRANCH: 'contributors-update'  # Target branch for changes
        PULL_REQUEST: 'main'  # Creates a PR to merge into main        